import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Bill } from '@/types';
import { formatCurrency, formatDate } from './mockData';

export function generateGSTInvoice(bill: Bill) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('GST INVOICE', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  // Bill Information
  const startY = 35;
  doc.text(`Invoice Date: ${formatDate(bill.date)}`, 14, startY);
  if (bill.dueDate) {
    doc.text(`Due Date: ${formatDate(bill.dueDate)}`, 14, startY + 6);
  }
  
  // Supplier Information
  const supplierName = (typeof bill.supplierId === 'object' && bill.supplierId 
    ? (bill.supplierId as any).name 
    : bill.supplier?.name) || "Unknown Supplier";

  doc.setFont('helvetica', 'bold');
  doc.text('Billed From:', pageWidth - 70, startY);
  doc.setFont('helvetica', 'normal');
  doc.text(supplierName, pageWidth - 70, startY + 6);
  if (typeof bill.supplierId === 'object' && (bill.supplierId as any).gstNumber) {
    doc.text(`GSTIN: ${(bill.supplierId as any).gstNumber}`, pageWidth - 70, startY + 12);
  }
  
  // Line Items
  let currentY = startY + 25;
  
  if (bill.items && bill.items.length > 0) {
    const tableData = bill.items.map((item: any) => [
      item.description || item.name || '',
      item.hsnCode || '-',
      item.quantity.toString(),
      `Rs. ${(item.unitPrice || item.price || 0).toFixed(2)}`,
      `${item.gstRate || 0}%`,
      item.gstType === 'IGST' ? 'IGST' : 'CGST+SGST',
      `Rs. ${(item.taxableAmount || (item.quantity * (item.price || 0))).toFixed(2)}`,
      `Rs. ${((item.cgst || 0) + (item.sgst || 0) + (item.igst || 0)).toFixed(2)}`,
      `Rs. ${(item.totalAmount || (item.quantity * (item.price || 0))).toFixed(2)}`
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [['Description', 'HSN', 'Qty', 'Unit Price', 'GST %', 'GST Type', 'Taxable', 'Tax', 'Total']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185], textColor: 255 },
      styles: { fontSize: 8, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 'auto' },
        2: { halign: 'right' },
        3: { halign: 'right' },
        4: { halign: 'center' },
        6: { halign: 'right' },
        7: { halign: 'right' },
        8: { halign: 'right' }
      }
    });
    
    currentY = (doc as any).lastAutoTable.finalY + 10;
  } else {
    doc.text('No line items recorded.', 14, currentY);
    currentY += 10;
  }
  
  // Totals Summary
  const totalsY = currentY;
  doc.setFont('helvetica', 'bold');
  doc.text('Summary:', 14, totalsY);
  doc.setFont('helvetica', 'normal');
  
  if (bill.subtotal !== undefined) {
    doc.text(`Taxable Amount: Rs. ${(bill as any).subtotal?.toFixed(2) || '0.00'}`, 14, totalsY + 6);
    doc.text(`CGST: Rs. ${(bill as any).totalCGST?.toFixed(2) || '0.00'}`, 14, totalsY + 12);
    doc.text(`SGST: Rs. ${(bill as any).totalSGST?.toFixed(2) || '0.00'}`, 14, totalsY + 18);
    doc.text(`IGST: Rs. ${(bill as any).totalIGST?.toFixed(2) || '0.00'}`, 14, totalsY + 24);
  }
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Grand Total: Rs. ${bill.amount.toFixed(2)}`, pageWidth - 70, totalsY + 6);
  
  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Digibill', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  
  // Save PDF
  doc.save(`Invoice_${supplierName.replace(/\s+/g, '_')}_${formatDate(bill.date).replace(/ /g, '_')}.pdf`);
}
