services:
  - type: web
    name: digibill-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
