import { useState, useEffect } from 'react';
import { supplierFetch } from '@/lib/supplierApi';
import type { SupplierBill } from '@/types/supplier-portal';
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { FileText, AlertCircle, ChevronLeft, ChevronRight } from 'lucide-react';
import { BillDetailSheet } from '@/components/supplier/BillDetailSheet';
import { DisputeDialog } from '@/components/supplier/DisputeDialog';
import { toast } from 'sonner';

export function SupplierBillsPage() {
  const [bills, setBills] = useState<SupplierBill[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  
  const [statusFilter, setStatusFilter] = useState('all');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  // Modals state
  const [selectedBill, setSelectedBill] = useState<SupplierBill | null>(null);
  const [isDetailOpen, setIsDetailOpen] = useState(false);
  const [isDisputeOpen, setIsDisputeOpen] = useState(false);
  const [billToDispute, setBillToDispute] = useState<SupplierBill | null>(null);

  const fetchBills = async () => {
    setIsLoading(true);
    try {
      let url = `/supplier-portal/bills?page=${page}&limit=10`;
      if (statusFilter !== 'all') {
        url += `&status=${statusFilter}`;
      }
      
      const response = await supplierFetch<{ success: boolean; data: { bills: SupplierBill[], pagination: any } }>(url);
      if (response.success) {
        setBills(response.data.bills);
        setTotalPages(response.data.pagination.pages || 1);
      }
    } catch (err: any) {
      if (err.message === 'Route not found' || err.status === 404) {
        setBills([]);
        setTotalPages(1);
      } else {
        setError(err.message || 'Failed to load bills');
      }
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchBills();
  }, [page, statusFilter]);

  const handleStatusChange = (value: string) => {
    setStatusFilter(value);
    setPage(1);
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', {
      maximumFractionDigits: 0
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-IN', {
      day: 'numeric',
      month: 'short',
      year: 'numeric'
    });
  };

  const handleAcknowledge = async (billId: string) => {
    try {
      const response = await supplierFetch<{ success: boolean; data: any }>(`/supplier-portal/bills/${billId}/acknowledge`, {
        method: 'POST'
      });
      if (response.success) {
        toast.success('Bill acknowledged successfully');
        fetchBills(); // refresh data
      }
    } catch (err: any) {
      toast.error(err.message || 'Failed to acknowledge bill');
    }
  };

  const openDispute = (bill: SupplierBill) => {
    setBillToDispute(bill);
    setIsDisputeOpen(true);
  };

  const viewDetails = (bill: SupplierBill) => {
    setSelectedBill(bill);
    setIsDetailOpen(true);
  };

  return (
    <div className="p-4 md:p-8 space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-foreground tracking-tight">My Bills</h1>
          <p className="text-muted-foreground mt-1">
            View, acknowledge, or dispute invoices generated by the shop.
          </p>
        </div>
      </div>

      <Tabs defaultValue="all" value={statusFilter} onValueChange={handleStatusChange} className="w-full">
        <TabsList className="grid w-full grid-cols-4 max-w-md">
          <TabsTrigger value="all">All</TabsTrigger>
          <TabsTrigger value="pending">Pending</TabsTrigger>
          <TabsTrigger value="paid">Paid</TabsTrigger>
          <TabsTrigger value="disputed">Disputed</TabsTrigger>
        </TabsList>
      </Tabs>

      {error ? (
        <div className="p-8 flex flex-col items-center justify-center text-center bg-muted/20 rounded-xl border border-border/50">
          <AlertCircle className="h-10 w-10 text-destructive mb-3" />
          <h3 className="font-semibold">Failed to load bills</h3>
          <p className="text-sm text-muted-foreground">{error}</p>
          <Button onClick={fetchBills} className="mt-4" variant="outline" size="sm">Retry</Button>
        </div>
      ) : isLoading ? (
        <div className="space-y-4">
          {[1, 2, 3, 4, 5].map((i) => (
            <Skeleton key={i} className="h-28 w-full rounded-xl" />
          ))}
        </div>
      ) : bills.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 text-center px-4 bg-muted/10 rounded-xl border border-dashed border-border">
          <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center mb-4">
            <FileText className="h-8 w-8 text-muted-foreground/50" />
          </div>
          <h3 className="text-lg font-semibold text-foreground">No bills found</h3>
          <p className="text-muted-foreground mt-1">
            There are no bills matching the current filters.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {/* Desktop Table View */}
          <Card className="hidden md:block overflow-hidden shadow-sm border-border/50">
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead className="text-xs text-muted-foreground uppercase bg-muted/30">
                  <tr>
                    <th className="px-6 py-4 font-semibold w-1/4">Description</th>
                    <th className="px-6 py-4 font-semibold">Amount</th>
                    <th className="px-6 py-4 font-semibold">Due Date</th>
                    <th className="px-6 py-4 font-semibold">Status</th>
                    <th className="px-6 py-4 font-semibold text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border/50">
                  {bills.map((bill) => (
                    <tr key={bill._id} className="hover:bg-muted/10 transition-colors group">
                      <td className="px-6 py-4 font-medium text-foreground">{bill.description}</td>
                      <td className="px-6 py-4 text-lg font-semibold tracking-tight">₹{formatCurrency(bill.amount)}</td>
                      <td className="px-6 py-4 text-muted-foreground">{formatDate(bill.dueDate)}</td>
                      <td className="px-6 py-4">
                        {bill.status === 'pending' && <Badge variant="outline" className="bg-orange-500/10 text-orange-600 border-orange-500/20">Pending</Badge>}
                        {bill.status === 'paid' && <Badge variant="outline" className="bg-green-500/10 text-green-600 border-green-500/20">Paid</Badge>}
                        {bill.status === 'disputed' && <Badge variant="outline" className="bg-destructive/10 text-destructive border-destructive/20">Disputed</Badge>}
                      </td>
                      <td className="px-6 py-4 text-right space-x-2 opacity-0 group-hover:opacity-100 transition-opacity">
                        <Button variant="outline" size="sm" onClick={() => viewDetails(bill)}>View Details</Button>
                        {!bill.acknowledgedAt && bill.status !== 'paid' && (
                          <Button size="sm" onClick={() => handleAcknowledge(bill._id)}>Acknowledge</Button>
                        )}
                        {!bill.dispute && bill.status !== 'paid' && (
                          <Button variant="destructive" size="sm" onClick={() => openDispute(bill)}>Dispute</Button>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>

          {/* Mobile Cards View */}
          <div className="md:hidden space-y-4">
            {bills.map((bill) => (
              <Card key={bill._id} className="shadow-sm border-border/50">
                <CardHeader className="pb-3 border-b border-border/50">
                  <div className="flex justify-between items-start">
                    <div>
                      <CardTitle className="text-xl font-bold tracking-tight">₹{formatCurrency(bill.amount)}</CardTitle>
                      <p className="text-sm text-muted-foreground mt-1">{bill.description}</p>
                    </div>
                    {bill.status === 'pending' && <Badge variant="outline" className="bg-orange-500/10 text-orange-600 border-orange-500/20">Pending</Badge>}
                    {bill.status === 'paid' && <Badge variant="outline" className="bg-green-500/10 text-green-600 border-green-500/20">Paid</Badge>}
                    {bill.status === 'disputed' && <Badge variant="outline" className="bg-destructive/10 text-destructive border-destructive/20">Disputed</Badge>}
                  </div>
                </CardHeader>
                <CardContent className="py-3 text-sm flex justify-between text-muted-foreground">
                  <span>Due: {formatDate(bill.dueDate)}</span>
                  {bill.acknowledgedAt && <span className="text-green-600 flex items-center gap-1"><CheckCircle2 className="h-3 w-3" /> Acknowledged</span>}
                </CardContent>
                <CardFooter className="pt-0 flex gap-2 flex-wrap">
                  <Button variant="outline" size="sm" className="flex-1" onClick={() => viewDetails(bill)}>View Details</Button>
                  {!bill.acknowledgedAt && bill.status !== 'paid' && (
                    <Button size="sm" className="flex-1" onClick={() => handleAcknowledge(bill._id)}>Acknowledge</Button>
                  )}
                  {!bill.dispute && bill.status !== 'paid' && (
                    <Button variant="destructive" size="sm" className="flex-1" onClick={() => openDispute(bill)}>Dispute</Button>
                  )}
                </CardFooter>
              </Card>
            ))}
          </div>

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between pt-4 border-t border-border/50">
              <p className="text-sm text-muted-foreground">
                Page {page} of {totalPages}
              </p>
              <div className="flex gap-2">
                <Button 
                  variant="outline" 
                  size="sm" 
                  onClick={() => setPage(p => Math.max(1, p - 1))}
                  disabled={page === 1}
                >
                  <ChevronLeft className="h-4 w-4 mr-1" /> Previous
                </Button>
                <Button 
                  variant="outline" 
                  size="sm" 
                  onClick={() => setPage(p => Math.min(totalPages, p + 1))}
                  disabled={page === totalPages}
                >
                  Next <ChevronRight className="h-4 w-4 ml-1" />
                </Button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Modals */}
      {selectedBill && (
        <BillDetailSheet 
          bill={selectedBill} 
          isOpen={isDetailOpen} 
          onClose={() => setIsDetailOpen(false)}
          onAcknowledge={handleAcknowledge}
          onDispute={() => {
            setIsDetailOpen(false);
            openDispute(selectedBill);
          }}
        />
      )}

      {billToDispute && (
        <DisputeDialog
          bill={billToDispute}
          isOpen={isDisputeOpen}
          onClose={() => setIsDisputeOpen(false)}
          onSuccess={() => {
            setIsDisputeOpen(false);
            fetchBills();
          }}
        />
      )}
    </div>
  );
}
